trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'Demo ML Routing - API - BUILD'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'Demo Account'
  rModelEndpoint: 'TBD'
  pythonModelEndpoint: 'TBD'
  sqlServerDatabase: 'TBD'
  sqlServerUserName: 'TBD'
  sqlServer: 'TBD'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'MLR-API-CI'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'demo-ml-routing-api-ci'
    resourceGroupName: 'demo-ml-routing-api-ci'
    storageAccountName: 'azmlrapici'
    region: 'East US'
    rModelEndpoint: ${{ variables.rModelEndpoint }}
    pythonModelEndpoint: ${{ variables.pythonModelEndpoint }}
    sqlServer: ${{ variables.sqlServer }}
    sqlServerDatabase: ${{ variables.sqlServerDatabase }}
    sqlServerUserName: ${{ variables.sqlServerUserName }}
    sqlServerPassword: ${{ variables.sqlServerPassword }}
    packageName: 'App.zip'
