parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: functionAppName
  default: ''
- name: resourceGroupName
  default: ''
- name: storageAccountName
  default: ''
- name: region
  default: ''
- name: rModelEndpoint
  default: ''
- name: pythonModelEndpoint
  default: ''
- name: sqlServer
  default: ''
- name: sqlServerDatabase
  default: ''
- name: sqlServerUserName
  default: ''
- name: sqlServerPassword
  default: ''
- name: packageName
  default: ''  

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureResourceGroupDeployment@2
              displayName: '1. Create Function Infrastructure'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/function-app-consumption.json'
                overrideParameters: '-name ${{ parameters.functionAppName }} -storageAccountName ${{ parameters.storageAccountName }} -linuxFxVersion "Python|3.6"'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - task: AzureFunctionApp@1
              displayName: '2. Azure functions app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: functionAppLinux
                appName: ${{ parameters.functionAppName }}
                package: '$(Pipeline.Workspace)/build/App/${{ parameters.packageName }}'
                AppSettings: '-R_MODEL_ENDPOINT	${{ parameters.rModelEndpoint }} -PYTHON_MODEL_ENDPOINT ${{ parameters.pythonModelEndpoint }} -SQL_SERVER ${{ parameters.sqlServer }} -SQL_DATABASE ${{ parameters.sqlServerDatabase }} -SQL_USERNAME ${{ parameters.sqlServerUserName }} -SQL_PASSWORD ${{ parameters.sqlServerPassword }}'